### ISSUE TITLE
compiling TFLite 1.13 for android28-arm64 with Android NDK r18b fails

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-mlperf#16]
I tried to build TFLite 1.13 for android28-arm64 with Android NDK r18b but it fails. I used the following commands:

```
$ ck detect soft:compiler.llvm.android.ndk --target_os=android28-arm64
$ ck install package --tags=lib,tflite,v1.13 --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=2 --target_os=android28-arm64
```

Here is the output:
[output.log](https://github.com/ctuning/ck-mlperf/files/3076200/output.log)

**Comment by psyhtest** [comment]
It's a duplicate of https://github.com/ctuning/ck-tensorflow/issues/106
