### ISSUE TITLE
Implement MLPerf ResNet50 package for TensorFlow

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-mlperf#2]
The [MLPerf ResNet50 reference](https://github.com/mlperf/inference/tree/master/cloud/image_classification) by @guschmue supports weights both in the [TensorFlow](https://zenodo.org/record/2535873/files/resnet50_v1.pb) and [ONNX](https://zenodo.org/record/2541184/files/resnet50_v1.onnx) formats. 

@guschmue notes:
> The benchmark is a reference implementation that is not meant to be the fastest implementation possible. It is written in python which might make it less suitable for lite models like mobilenet or large number of cpu's. We are thinking to provide a c++ implementation with identical functionality in the near future.

In fact, we already have such an implementation wrapped in CK: [ck-tensorflow:program:image-classification-tf-cpp](https://github.com/ctuning/ck-tensorflow/tree/master/program/image-classification-tf-cpp). Let's check it works with the ResNet50 weights in the TensorFlow format by providing a CK package.

**Comment by psyhtest** [comment]
I vaguely recall that the CK implementation uses `*.ckpt` files, while the reference one needs a `*.pb` file. However, the [official TF ResNet50 page](https://github.com/tensorflow/models/tree/master/official/resnet) also mentions `*.ckpt`. It appears we need the checkpoint listed as "ResNet-50 v1 (fp32, Accuracy 76.53%)" ("v1" means "v1.5", as explained there).

**Comment by psyhtest** [comment]
We should also check if [SavedModels](https://www.tensorflow.org/guide/saved_model) is something we might want to support as well (perhaps to be converted to [TFLite](https://www.tensorflow.org/lite/convert) or to proprietary inference engines).

**Comment by psyhtest** [comment]
For reference, this is [how](https://github.com/mlperf/inference/blob/master/edge/object_classification/mobilenets/tf-cpp/README.md) `program:image-classification-tf-cpp` is used in the MLPerf MobileNet reference.

**Comment by ens-lg4** [comment]
The package `ck-tensorflow:package:tensorflowmodel-resnet50-v1.5-mlperf` has been implemented and `program:image-classification-tf-cpp` agrees to take it as input.
