### ISSUE TITLE
Implement MLPerf image classification program for ONNX

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-mlperf#3]
We should implement `cl-mlperf:program:image-classification-onnx` similar to 
[`ck-tensorflow:program:image-classification-tflite`](https://github.com/ctuning/ck-tensorflow/tree/master/program/image-classification-tflite) and friends to support MLPerf image classification models in the ONNX format (e.g. [ResNet50](https://github.com/mlperf/inference/tree/master/cloud/image_classification)). Perhaps [main.py](https://github.com/mlperf/inference/blob/master/cloud/image_classification/python/main.py) already does all we need, just needs to have its inputs and outputs unified with `program:image-classification-tflite`.

**Comment by ens-lg4** [comment]
Done, see `program:image-classification-onnx-py` .
It supports both NHWC and NCHW models (tested).
